/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit_merchant_api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.gotit_merchant_api.JSON;

/**
 * RequestUnReservedBodySchema
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-30T16:00:27.551247+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.12.0")
public class RequestUnReservedBodySchema {
  public static final String SERIALIZED_NAME_PIN = "pin";
  @SerializedName(SERIALIZED_NAME_PIN)
  @javax.annotation.Nullable
  private String pin;

  public static final String SERIALIZED_NAME_CODES = "codes";
  @SerializedName(SERIALIZED_NAME_CODES)
  @javax.annotation.Nullable
  private List<String> codes = new ArrayList<>();

  public static final String SERIALIZED_NAME_BILL_NUMBER = "bill_number";
  @SerializedName(SERIALIZED_NAME_BILL_NUMBER)
  @javax.annotation.Nullable
  private String billNumber;

  public static final String SERIALIZED_NAME_BILL_CREATED_AT = "bill_created_at";
  @SerializedName(SERIALIZED_NAME_BILL_CREATED_AT)
  @javax.annotation.Nullable
  private String billCreatedAt;

  public RequestUnReservedBodySchema() {
  }

  public RequestUnReservedBodySchema pin(@javax.annotation.Nullable String pin) {
    this.pin = pin;
    return this;
  }

  /**
   * Store pin
   * @return pin
   */
  @javax.annotation.Nullable
  public String getPin() {
    return pin;
  }

  public void setPin(@javax.annotation.Nullable String pin) {
    this.pin = pin;
  }


  public RequestUnReservedBodySchema codes(@javax.annotation.Nullable List<String> codes) {
    this.codes = codes;
    return this;
  }

  public RequestUnReservedBodySchema addCodesItem(String codesItem) {
    if (this.codes == null) {
      this.codes = new ArrayList<>();
    }
    this.codes.add(codesItem);
    return this;
  }

  /**
   * Array of 10-16 characters Got It voucher codes
   * @return codes
   */
  @javax.annotation.Nullable
  public List<String> getCodes() {
    return codes;
  }

  public void setCodes(@javax.annotation.Nullable List<String> codes) {
    this.codes = codes;
  }


  public RequestUnReservedBodySchema billNumber(@javax.annotation.Nullable String billNumber) {
    this.billNumber = billNumber;
    return this;
  }

  /**
   * Bill number will apply vouchers
   * @return billNumber
   */
  @javax.annotation.Nullable
  public String getBillNumber() {
    return billNumber;
  }

  public void setBillNumber(@javax.annotation.Nullable String billNumber) {
    this.billNumber = billNumber;
  }


  public RequestUnReservedBodySchema billCreatedAt(@javax.annotation.Nullable String billCreatedAt) {
    this.billCreatedAt = billCreatedAt;
    return this;
  }

  /**
   * Bill creation time. Format: YYYY-MM-DD HH:MM:SS
   * @return billCreatedAt
   */
  @javax.annotation.Nullable
  public String getBillCreatedAt() {
    return billCreatedAt;
  }

  public void setBillCreatedAt(@javax.annotation.Nullable String billCreatedAt) {
    this.billCreatedAt = billCreatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestUnReservedBodySchema requestUnReservedBodySchema = (RequestUnReservedBodySchema) o;
    return Objects.equals(this.pin, requestUnReservedBodySchema.pin) &&
        Objects.equals(this.codes, requestUnReservedBodySchema.codes) &&
        Objects.equals(this.billNumber, requestUnReservedBodySchema.billNumber) &&
        Objects.equals(this.billCreatedAt, requestUnReservedBodySchema.billCreatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pin, codes, billNumber, billCreatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestUnReservedBodySchema {\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    codes: ").append(toIndentedString(codes)).append("\n");
    sb.append("    billNumber: ").append(toIndentedString(billNumber)).append("\n");
    sb.append("    billCreatedAt: ").append(toIndentedString(billCreatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pin");
    openapiFields.add("codes");
    openapiFields.add("bill_number");
    openapiFields.add("bill_created_at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RequestUnReservedBodySchema
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RequestUnReservedBodySchema.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RequestUnReservedBodySchema is not found in the empty JSON string", RequestUnReservedBodySchema.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RequestUnReservedBodySchema.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RequestUnReservedBodySchema` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("pin") != null && !jsonObj.get("pin").isJsonNull()) && !jsonObj.get("pin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pin").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("codes") != null && !jsonObj.get("codes").isJsonNull() && !jsonObj.get("codes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `codes` to be an array in the JSON string but got `%s`", jsonObj.get("codes").toString()));
      }
      if ((jsonObj.get("bill_number") != null && !jsonObj.get("bill_number").isJsonNull()) && !jsonObj.get("bill_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bill_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bill_number").toString()));
      }
      if ((jsonObj.get("bill_created_at") != null && !jsonObj.get("bill_created_at").isJsonNull()) && !jsonObj.get("bill_created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bill_created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bill_created_at").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RequestUnReservedBodySchema.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RequestUnReservedBodySchema' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RequestUnReservedBodySchema> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RequestUnReservedBodySchema.class));

       return (TypeAdapter<T>) new TypeAdapter<RequestUnReservedBodySchema>() {
           @Override
           public void write(JsonWriter out, RequestUnReservedBodySchema value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RequestUnReservedBodySchema read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RequestUnReservedBodySchema given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RequestUnReservedBodySchema
   * @throws IOException if the JSON string is invalid with respect to RequestUnReservedBodySchema
   */
  public static RequestUnReservedBodySchema fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RequestUnReservedBodySchema.class);
  }

  /**
   * Convert an instance of RequestUnReservedBodySchema to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

