/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit_merchant_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RequestUnReservedBodySchema
 */
public class RequestUnReservedBodySchemaTest {
    private final RequestUnReservedBodySchema model = new RequestUnReservedBodySchema();

    /**
     * Model tests for RequestUnReservedBodySchema
     */
    @Test
    public void testRequestUnReservedBodySchema() {
        // TODO: test RequestUnReservedBodySchema
    }

    /**
     * Test the property 'pin'
     */
    @Test
    public void pinTest() {
        // TODO: test pin
    }

    /**
     * Test the property 'codes'
     */
    @Test
    public void codesTest() {
        // TODO: test codes
    }

    /**
     * Test the property 'billNumber'
     */
    @Test
    public void billNumberTest() {
        // TODO: test billNumber
    }

    /**
     * Test the property 'billCreatedAt'
     */
    @Test
    public void billCreatedAtTest() {
        // TODO: test billCreatedAt
    }

}
