/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit_merchant_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
 */
public class ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInnerTest {
    private final ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner model = new ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner();

    /**
     * Model tests for ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
     */
    @Test
    public void testResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner() {
        // TODO: test ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

}
