/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit_merchant_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit_merchant_api.model.ResponseCheckMultipleSchemaDataInnerConditions;
import com.gotit_merchant_api.model.ResponseCheckMultipleSchemaDataInnerRedemptions;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseCheckMultipleSchemaDataInner
 */
public class ResponseCheckMultipleSchemaDataInnerTest {
    private final ResponseCheckMultipleSchemaDataInner model = new ResponseCheckMultipleSchemaDataInner();

    /**
     * Model tests for ResponseCheckMultipleSchemaDataInner
     */
    @Test
    public void testResponseCheckMultipleSchemaDataInner() {
        // TODO: test ResponseCheckMultipleSchemaDataInner
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'voucherType'
     */
    @Test
    public void voucherTypeTest() {
        // TODO: test voucherType
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'cancelDate'
     */
    @Test
    public void cancelDateTest() {
        // TODO: test cancelDate
    }

    /**
     * Test the property 'conditions'
     */
    @Test
    public void conditionsTest() {
        // TODO: test conditions
    }

    /**
     * Test the property 'redemptions'
     */
    @Test
    public void redemptionsTest() {
        // TODO: test redemptions
    }

}
