/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit_merchant_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit_merchant_api.model.ResponseCheckMultipleSchemaDataInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseCheckMultipleSchema
 */
public class ResponseCheckMultipleSchemaTest {
    private final ResponseCheckMultipleSchema model = new ResponseCheckMultipleSchema();

    /**
     * Model tests for ResponseCheckMultipleSchema
     */
    @Test
    public void testResponseCheckMultipleSchema() {
        // TODO: test ResponseCheckMultipleSchema
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'returnCode'
     */
    @Test
    public void returnCodeTest() {
        // TODO: test returnCode
    }

    /**
     * Test the property 'messageEn'
     */
    @Test
    public void messageEnTest() {
        // TODO: test messageEn
    }

    /**
     * Test the property 'messageVi'
     */
    @Test
    public void messageViTest() {
        // TODO: test messageVi
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
