/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit_merchant_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseReservedSchemaUsedStore
 */
public class ResponseReservedSchemaUsedStoreTest {
    private final ResponseReservedSchemaUsedStore model = new ResponseReservedSchemaUsedStore();

    /**
     * Model tests for ResponseReservedSchemaUsedStore
     */
    @Test
    public void testResponseReservedSchemaUsedStore() {
        // TODO: test ResponseReservedSchemaUsedStore
    }

    /**
     * Test the property 'nameVi'
     */
    @Test
    public void nameViTest() {
        // TODO: test nameVi
    }

    /**
     * Test the property 'nameEn'
     */
    @Test
    public void nameEnTest() {
        // TODO: test nameEn
    }

}
