/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit_merchant_api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit_merchant_api.model.ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner;
import com.gotit_merchant_api.model.ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseMarkUseMultipleSchemaDataInnerRedemptions
 */
public class ResponseMarkUseMultipleSchemaDataInnerRedemptionsTest {
    private final ResponseMarkUseMultipleSchemaDataInnerRedemptions model = new ResponseMarkUseMultipleSchemaDataInnerRedemptions();

    /**
     * Model tests for ResponseMarkUseMultipleSchemaDataInnerRedemptions
     */
    @Test
    public void testResponseMarkUseMultipleSchemaDataInnerRedemptions() {
        // TODO: test ResponseMarkUseMultipleSchemaDataInnerRedemptions
    }

    /**
     * Test the property 'redeemSkuCodes'
     */
    @Test
    public void redeemSkuCodesTest() {
        // TODO: test redeemSkuCodes
    }

    /**
     * Test the property 'redemptionValue'
     */
    @Test
    public void redemptionValueTest() {
        // TODO: test redemptionValue
    }

    /**
     * Test the property 'usedStore'
     */
    @Test
    public void usedStoreTest() {
        // TODO: test usedStore
    }

    /**
     * Test the property 'usedDate'
     */
    @Test
    public void usedDateTest() {
        // TODO: test usedDate
    }

}
