/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RequestCheckMultipleBodySchemaSkusInfoInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RequestMarkUseMultipleBodySchema
 */
public class RequestMarkUseMultipleBodySchemaTest {
    private final RequestMarkUseMultipleBodySchema model = new RequestMarkUseMultipleBodySchema();

    /**
     * Model tests for RequestMarkUseMultipleBodySchema
     */
    @Test
    public void testRequestMarkUseMultipleBodySchema() {
        // TODO: test RequestMarkUseMultipleBodySchema
    }

    /**
     * Test the property 'pin'
     */
    @Test
    public void pinTest() {
        // TODO: test pin
    }

    /**
     * Test the property 'codes'
     */
    @Test
    public void codesTest() {
        // TODO: test codes
    }

    /**
     * Test the property 'billNumber'
     */
    @Test
    public void billNumberTest() {
        // TODO: test billNumber
    }

    /**
     * Test the property 'totalBill'
     */
    @Test
    public void totalBillTest() {
        // TODO: test totalBill
    }

    /**
     * Test the property 'skipReservedWhenMarkUsed'
     */
    @Test
    public void skipReservedWhenMarkUsedTest() {
        // TODO: test skipReservedWhenMarkUsed
    }

    /**
     * Test the property 'skusInfo'
     */
    @Test
    public void skusInfoTest() {
        // TODO: test skusInfo
    }

}
