/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseCheckMultipleSchemaDataInnerConditions
 */
public class ResponseCheckMultipleSchemaDataInnerConditionsTest {
    private final ResponseCheckMultipleSchemaDataInnerConditions model = new ResponseCheckMultipleSchemaDataInnerConditions();

    /**
     * Model tests for ResponseCheckMultipleSchemaDataInnerConditions
     */
    @Test
    public void testResponseCheckMultipleSchemaDataInnerConditions() {
        // TODO: test ResponseCheckMultipleSchemaDataInnerConditions
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'excludeSpecificDate'
     */
    @Test
    public void excludeSpecificDateTest() {
        // TODO: test excludeSpecificDate
    }

    /**
     * Test the property 'excludeRecurringDay'
     */
    @Test
    public void excludeRecurringDayTest() {
        // TODO: test excludeRecurringDay
    }

    /**
     * Test the property 'redeemableSkus'
     */
    @Test
    public void redeemableSkusTest() {
        // TODO: test redeemableSkus
    }

}
