/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner;
import org.openapitools.client.model.ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseCheckMultipleSchemaDataInnerRedemptions
 */
public class ResponseCheckMultipleSchemaDataInnerRedemptionsTest {
    private final ResponseCheckMultipleSchemaDataInnerRedemptions model = new ResponseCheckMultipleSchemaDataInnerRedemptions();

    /**
     * Model tests for ResponseCheckMultipleSchemaDataInnerRedemptions
     */
    @Test
    public void testResponseCheckMultipleSchemaDataInnerRedemptions() {
        // TODO: test ResponseCheckMultipleSchemaDataInnerRedemptions
    }

    /**
     * Test the property 'redeemSkuCodes'
     */
    @Test
    public void redeemSkuCodesTest() {
        // TODO: test redeemSkuCodes
    }

    /**
     * Test the property 'redemptionValue'
     */
    @Test
    public void redemptionValueTest() {
        // TODO: test redemptionValue
    }

    /**
     * Test the property 'usedStore'
     */
    @Test
    public void usedStoreTest() {
        // TODO: test usedStore
    }

    /**
     * Test the property 'usedDate'
     */
    @Test
    public void usedDateTest() {
        // TODO: test usedDate
    }

    /**
     * Test the property 'billNumber'
     */
    @Test
    public void billNumberTest() {
        // TODO: test billNumber
    }

}
