/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseMarkUseMultipleSchemaDataInnerConditions
 */
public class ResponseMarkUseMultipleSchemaDataInnerConditionsTest {
    private final ResponseMarkUseMultipleSchemaDataInnerConditions model = new ResponseMarkUseMultipleSchemaDataInnerConditions();

    /**
     * Model tests for ResponseMarkUseMultipleSchemaDataInnerConditions
     */
    @Test
    public void testResponseMarkUseMultipleSchemaDataInnerConditions() {
        // TODO: test ResponseMarkUseMultipleSchemaDataInnerConditions
    }

    /**
     * Test the property 'redeemableSkus'
     */
    @Test
    public void redeemableSkusTest() {
        // TODO: test redeemableSkus
    }

}
