/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore
 */
public class ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStoreTest {
    private final ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore model = new ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore();

    /**
     * Model tests for ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore
     */
    @Test
    public void testResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore() {
        // TODO: test ResponseCheckMultipleSchemaDataInnerRedemptionsUsedStore
    }

    /**
     * Test the property 'nameVi'
     */
    @Test
    public void nameViTest() {
        // TODO: test nameVi
    }

    /**
     * Test the property 'nameEn'
     */
    @Test
    public void nameEnTest() {
        // TODO: test nameEn
    }

}
