/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Store marked voucher used/reserved
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:25:42.013225+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class ResponseReservedSchemaUsedStore {
  public static final String SERIALIZED_NAME_NAME_VI = "name_vi";
  @SerializedName(SERIALIZED_NAME_NAME_VI)
  @javax.annotation.Nullable
  private String nameVi;

  public static final String SERIALIZED_NAME_NAME_EN = "name_en";
  @SerializedName(SERIALIZED_NAME_NAME_EN)
  @javax.annotation.Nullable
  private String nameEn;

  public ResponseReservedSchemaUsedStore() {
  }

  public ResponseReservedSchemaUsedStore nameVi(@javax.annotation.Nullable String nameVi) {
    this.nameVi = nameVi;
    return this;
  }

  /**
   * Store name in Vietnamese
   * @return nameVi
   */
  @javax.annotation.Nullable
  public String getNameVi() {
    return nameVi;
  }

  public void setNameVi(@javax.annotation.Nullable String nameVi) {
    this.nameVi = nameVi;
  }


  public ResponseReservedSchemaUsedStore nameEn(@javax.annotation.Nullable String nameEn) {
    this.nameEn = nameEn;
    return this;
  }

  /**
   * Store name in English
   * @return nameEn
   */
  @javax.annotation.Nullable
  public String getNameEn() {
    return nameEn;
  }

  public void setNameEn(@javax.annotation.Nullable String nameEn) {
    this.nameEn = nameEn;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseReservedSchemaUsedStore responseReservedSchemaUsedStore = (ResponseReservedSchemaUsedStore) o;
    return Objects.equals(this.nameVi, responseReservedSchemaUsedStore.nameVi) &&
        Objects.equals(this.nameEn, responseReservedSchemaUsedStore.nameEn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameVi, nameEn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseReservedSchemaUsedStore {\n");
    sb.append("    nameVi: ").append(toIndentedString(nameVi)).append("\n");
    sb.append("    nameEn: ").append(toIndentedString(nameEn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name_vi");
    openapiFields.add("name_en");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResponseReservedSchemaUsedStore
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResponseReservedSchemaUsedStore.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResponseReservedSchemaUsedStore is not found in the empty JSON string", ResponseReservedSchemaUsedStore.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResponseReservedSchemaUsedStore.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResponseReservedSchemaUsedStore` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name_vi") != null && !jsonObj.get("name_vi").isJsonNull()) && !jsonObj.get("name_vi").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name_vi` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name_vi").toString()));
      }
      if ((jsonObj.get("name_en") != null && !jsonObj.get("name_en").isJsonNull()) && !jsonObj.get("name_en").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name_en` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name_en").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResponseReservedSchemaUsedStore.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResponseReservedSchemaUsedStore' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResponseReservedSchemaUsedStore> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResponseReservedSchemaUsedStore.class));

       return (TypeAdapter<T>) new TypeAdapter<ResponseReservedSchemaUsedStore>() {
           @Override
           public void write(JsonWriter out, ResponseReservedSchemaUsedStore value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResponseReservedSchemaUsedStore read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResponseReservedSchemaUsedStore given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResponseReservedSchemaUsedStore
   * @throws IOException if the JSON string is invalid with respect to ResponseReservedSchemaUsedStore
   */
  public static ResponseReservedSchemaUsedStore fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResponseReservedSchemaUsedStore.class);
  }

  /**
   * Convert an instance of ResponseReservedSchemaUsedStore to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

