/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-20T18:05:09.722690784+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner {
  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  @javax.annotation.Nullable
  private String sku;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  @javax.annotation.Nullable
  private Integer quantity;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nullable
  private Integer price;

  public ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner() {
  }

  public ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner sku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * SKU code is redeemed for voucher
   * @return sku
   */
  @javax.annotation.Nullable
  public String getSku() {
    return sku;
  }

  public void setSku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
  }


  public ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner quantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * SKU quantity is redeemed for voucher
   * @return quantity
   */
  @javax.annotation.Nullable
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
  }


  public ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner price(@javax.annotation.Nullable Integer price) {
    this.price = price;
    return this;
  }

  /**
   * Selling price of SKU in bill.
   * @return price
   */
  @javax.annotation.Nullable
  public Integer getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nullable Integer price) {
    this.price = price;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner responseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner = (ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner) o;
    return Objects.equals(this.sku, responseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.sku) &&
        Objects.equals(this.quantity, responseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.quantity) &&
        Objects.equals(this.price, responseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sku, quantity, price);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner {\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sku");
    openapiFields.add("quantity");
    openapiFields.add("price");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner is not found in the empty JSON string", ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("sku") != null && !jsonObj.get("sku").isJsonNull()) && !jsonObj.get("sku").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sku` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sku").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner>() {
           @Override
           public void write(JsonWriter out, ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
   * @throws IOException if the JSON string is invalid with respect to ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
   */
  public static ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner.class);
  }

  /**
   * Convert an instance of ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

