/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ResponseCheckMultipleSchemaDataInnerConditions;
import org.openapitools.client.model.ResponseCheckMultipleSchemaDataInnerRedemptions;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ResponseCheckMultipleSchemaDataInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-26T14:02:03.006856+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class ResponseCheckMultipleSchemaDataInner {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private String code;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nullable
  private Integer value;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nullable
  private Integer state;

  public static final String SERIALIZED_NAME_VOUCHER_TYPE = "voucher_type";
  @SerializedName(SERIALIZED_NAME_VOUCHER_TYPE)
  @javax.annotation.Nullable
  private String voucherType;

  public static final String SERIALIZED_NAME_EXPIRY_DATE = "expiry_date";
  @SerializedName(SERIALIZED_NAME_EXPIRY_DATE)
  @javax.annotation.Nullable
  private String expiryDate;

  public static final String SERIALIZED_NAME_CANCEL_DATE = "cancel_date";
  @SerializedName(SERIALIZED_NAME_CANCEL_DATE)
  @javax.annotation.Nullable
  private String cancelDate;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  @javax.annotation.Nullable
  private ResponseCheckMultipleSchemaDataInnerConditions conditions;

  public static final String SERIALIZED_NAME_REDEMPTIONS = "redemptions";
  @SerializedName(SERIALIZED_NAME_REDEMPTIONS)
  @javax.annotation.Nullable
  private ResponseCheckMultipleSchemaDataInnerRedemptions redemptions;

  public ResponseCheckMultipleSchemaDataInner() {
  }

  public ResponseCheckMultipleSchemaDataInner code(@javax.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * Voucher code
   * @return code
   */
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public ResponseCheckMultipleSchemaDataInner value(@javax.annotation.Nullable Integer value) {
    this.value = value;
    return this;
  }

  /**
   * Value of voucher
   * @return value
   */
  @javax.annotation.Nullable
  public Integer getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nullable Integer value) {
    this.value = value;
  }


  public ResponseCheckMultipleSchemaDataInner state(@javax.annotation.Nullable Integer state) {
    this.state = state;
    return this;
  }

  /**
   * State of voucher
   * @return state
   */
  @javax.annotation.Nullable
  public Integer getState() {
    return state;
  }

  public void setState(@javax.annotation.Nullable Integer state) {
    this.state = state;
  }


  public ResponseCheckMultipleSchemaDataInner voucherType(@javax.annotation.Nullable String voucherType) {
    this.voucherType = voucherType;
    return this;
  }

  /**
   * Voucher type, standard or conditional
   * @return voucherType
   */
  @javax.annotation.Nullable
  public String getVoucherType() {
    return voucherType;
  }

  public void setVoucherType(@javax.annotation.Nullable String voucherType) {
    this.voucherType = voucherType;
  }


  public ResponseCheckMultipleSchemaDataInner expiryDate(@javax.annotation.Nullable String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

  /**
   * Expiry date of voucher (YYYY-MM-DD)
   * @return expiryDate
   */
  @javax.annotation.Nullable
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(@javax.annotation.Nullable String expiryDate) {
    this.expiryDate = expiryDate;
  }


  public ResponseCheckMultipleSchemaDataInner cancelDate(@javax.annotation.Nullable String cancelDate) {
    this.cancelDate = cancelDate;
    return this;
  }

  /**
   * Date cancel voucher (YYYY-MM-DD)
   * @return cancelDate
   */
  @javax.annotation.Nullable
  public String getCancelDate() {
    return cancelDate;
  }

  public void setCancelDate(@javax.annotation.Nullable String cancelDate) {
    this.cancelDate = cancelDate;
  }


  public ResponseCheckMultipleSchemaDataInner conditions(@javax.annotation.Nullable ResponseCheckMultipleSchemaDataInnerConditions conditions) {
    this.conditions = conditions;
    return this;
  }

  /**
   * Get conditions
   * @return conditions
   */
  @javax.annotation.Nullable
  public ResponseCheckMultipleSchemaDataInnerConditions getConditions() {
    return conditions;
  }

  public void setConditions(@javax.annotation.Nullable ResponseCheckMultipleSchemaDataInnerConditions conditions) {
    this.conditions = conditions;
  }


  public ResponseCheckMultipleSchemaDataInner redemptions(@javax.annotation.Nullable ResponseCheckMultipleSchemaDataInnerRedemptions redemptions) {
    this.redemptions = redemptions;
    return this;
  }

  /**
   * Get redemptions
   * @return redemptions
   */
  @javax.annotation.Nullable
  public ResponseCheckMultipleSchemaDataInnerRedemptions getRedemptions() {
    return redemptions;
  }

  public void setRedemptions(@javax.annotation.Nullable ResponseCheckMultipleSchemaDataInnerRedemptions redemptions) {
    this.redemptions = redemptions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseCheckMultipleSchemaDataInner responseCheckMultipleSchemaDataInner = (ResponseCheckMultipleSchemaDataInner) o;
    return Objects.equals(this.code, responseCheckMultipleSchemaDataInner.code) &&
        Objects.equals(this.value, responseCheckMultipleSchemaDataInner.value) &&
        Objects.equals(this.state, responseCheckMultipleSchemaDataInner.state) &&
        Objects.equals(this.voucherType, responseCheckMultipleSchemaDataInner.voucherType) &&
        Objects.equals(this.expiryDate, responseCheckMultipleSchemaDataInner.expiryDate) &&
        Objects.equals(this.cancelDate, responseCheckMultipleSchemaDataInner.cancelDate) &&
        Objects.equals(this.conditions, responseCheckMultipleSchemaDataInner.conditions) &&
        Objects.equals(this.redemptions, responseCheckMultipleSchemaDataInner.redemptions);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, value, state, voucherType, expiryDate, cancelDate, conditions, redemptions);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseCheckMultipleSchemaDataInner {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    voucherType: ").append(toIndentedString(voucherType)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    cancelDate: ").append(toIndentedString(cancelDate)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    redemptions: ").append(toIndentedString(redemptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("code");
    openapiFields.add("value");
    openapiFields.add("state");
    openapiFields.add("voucher_type");
    openapiFields.add("expiry_date");
    openapiFields.add("cancel_date");
    openapiFields.add("conditions");
    openapiFields.add("redemptions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResponseCheckMultipleSchemaDataInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResponseCheckMultipleSchemaDataInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResponseCheckMultipleSchemaDataInner is not found in the empty JSON string", ResponseCheckMultipleSchemaDataInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResponseCheckMultipleSchemaDataInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResponseCheckMultipleSchemaDataInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if ((jsonObj.get("voucher_type") != null && !jsonObj.get("voucher_type").isJsonNull()) && !jsonObj.get("voucher_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voucher_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voucher_type").toString()));
      }
      if ((jsonObj.get("expiry_date") != null && !jsonObj.get("expiry_date").isJsonNull()) && !jsonObj.get("expiry_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expiry_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiry_date").toString()));
      }
      if ((jsonObj.get("cancel_date") != null && !jsonObj.get("cancel_date").isJsonNull()) && !jsonObj.get("cancel_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cancel_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancel_date").toString()));
      }
      // validate the optional field `conditions`
      if (jsonObj.get("conditions") != null && !jsonObj.get("conditions").isJsonNull()) {
        ResponseCheckMultipleSchemaDataInnerConditions.validateJsonElement(jsonObj.get("conditions"));
      }
      // validate the optional field `redemptions`
      if (jsonObj.get("redemptions") != null && !jsonObj.get("redemptions").isJsonNull()) {
        ResponseCheckMultipleSchemaDataInnerRedemptions.validateJsonElement(jsonObj.get("redemptions"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResponseCheckMultipleSchemaDataInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResponseCheckMultipleSchemaDataInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResponseCheckMultipleSchemaDataInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResponseCheckMultipleSchemaDataInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ResponseCheckMultipleSchemaDataInner>() {
           @Override
           public void write(JsonWriter out, ResponseCheckMultipleSchemaDataInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResponseCheckMultipleSchemaDataInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResponseCheckMultipleSchemaDataInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResponseCheckMultipleSchemaDataInner
   * @throws IOException if the JSON string is invalid with respect to ResponseCheckMultipleSchemaDataInner
   */
  public static ResponseCheckMultipleSchemaDataInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResponseCheckMultipleSchemaDataInner.class);
  }

  /**
   * Convert an instance of ResponseCheckMultipleSchemaDataInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

