/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Include information involve with voucher type is conditional
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:25:42.013225+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class ResponseMarkUseMultipleSchemaDataInnerConditions {
  public static final String SERIALIZED_NAME_REDEEMABLE_SKUS = "redeemable_skus";
  @SerializedName(SERIALIZED_NAME_REDEEMABLE_SKUS)
  @javax.annotation.Nullable
  private List<String> redeemableSkus = new ArrayList<>();

  public ResponseMarkUseMultipleSchemaDataInnerConditions() {
  }

  public ResponseMarkUseMultipleSchemaDataInnerConditions redeemableSkus(@javax.annotation.Nullable List<String> redeemableSkus) {
    this.redeemableSkus = redeemableSkus;
    return this;
  }

  public ResponseMarkUseMultipleSchemaDataInnerConditions addRedeemableSkusItem(String redeemableSkusItem) {
    if (this.redeemableSkus == null) {
      this.redeemableSkus = new ArrayList<>();
    }
    this.redeemableSkus.add(redeemableSkusItem);
    return this;
  }

  /**
   * List of redeemable SKUs of the voucher code. For voucher type &#x3D; conditional, bill number must contain at least 1 redeemable SKU of the voucher.
   * @return redeemableSkus
   */
  @javax.annotation.Nullable
  public List<String> getRedeemableSkus() {
    return redeemableSkus;
  }

  public void setRedeemableSkus(@javax.annotation.Nullable List<String> redeemableSkus) {
    this.redeemableSkus = redeemableSkus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseMarkUseMultipleSchemaDataInnerConditions responseMarkUseMultipleSchemaDataInnerConditions = (ResponseMarkUseMultipleSchemaDataInnerConditions) o;
    return Objects.equals(this.redeemableSkus, responseMarkUseMultipleSchemaDataInnerConditions.redeemableSkus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redeemableSkus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseMarkUseMultipleSchemaDataInnerConditions {\n");
    sb.append("    redeemableSkus: ").append(toIndentedString(redeemableSkus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("redeemable_skus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResponseMarkUseMultipleSchemaDataInnerConditions
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResponseMarkUseMultipleSchemaDataInnerConditions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResponseMarkUseMultipleSchemaDataInnerConditions is not found in the empty JSON string", ResponseMarkUseMultipleSchemaDataInnerConditions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResponseMarkUseMultipleSchemaDataInnerConditions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResponseMarkUseMultipleSchemaDataInnerConditions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("redeemable_skus") != null && !jsonObj.get("redeemable_skus").isJsonNull() && !jsonObj.get("redeemable_skus").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `redeemable_skus` to be an array in the JSON string but got `%s`", jsonObj.get("redeemable_skus").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResponseMarkUseMultipleSchemaDataInnerConditions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResponseMarkUseMultipleSchemaDataInnerConditions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResponseMarkUseMultipleSchemaDataInnerConditions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResponseMarkUseMultipleSchemaDataInnerConditions.class));

       return (TypeAdapter<T>) new TypeAdapter<ResponseMarkUseMultipleSchemaDataInnerConditions>() {
           @Override
           public void write(JsonWriter out, ResponseMarkUseMultipleSchemaDataInnerConditions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResponseMarkUseMultipleSchemaDataInnerConditions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResponseMarkUseMultipleSchemaDataInnerConditions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResponseMarkUseMultipleSchemaDataInnerConditions
   * @throws IOException if the JSON string is invalid with respect to ResponseMarkUseMultipleSchemaDataInnerConditions
   */
  public static ResponseMarkUseMultipleSchemaDataInnerConditions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResponseMarkUseMultipleSchemaDataInnerConditions.class);
  }

  /**
   * Convert an instance of ResponseMarkUseMultipleSchemaDataInnerConditions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

