/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ResponseMarkUseMultipleSchemaDataInner;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ResponseMarkUseMultipleSchema
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-20T18:05:09.722690784+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class ResponseMarkUseMultipleSchema {
  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  @javax.annotation.Nullable
  private Boolean success;

  public static final String SERIALIZED_NAME_RETURN_CODE = "return_code";
  @SerializedName(SERIALIZED_NAME_RETURN_CODE)
  @javax.annotation.Nullable
  private String returnCode;

  public static final String SERIALIZED_NAME_MESSAGE_EN = "message_en";
  @SerializedName(SERIALIZED_NAME_MESSAGE_EN)
  @javax.annotation.Nullable
  private String messageEn;

  public static final String SERIALIZED_NAME_MESSAGE_VI = "message_vi";
  @SerializedName(SERIALIZED_NAME_MESSAGE_VI)
  @javax.annotation.Nullable
  private String messageVi;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nullable
  private List<ResponseMarkUseMultipleSchemaDataInner> data = new ArrayList<>();

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transaction_id";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  @javax.annotation.Nullable
  private String transactionId;

  public static final String SERIALIZED_NAME_BILL_NUMBER = "bill_number";
  @SerializedName(SERIALIZED_NAME_BILL_NUMBER)
  @javax.annotation.Nullable
  private String billNumber;

  public ResponseMarkUseMultipleSchema() {
  }

  public ResponseMarkUseMultipleSchema success(@javax.annotation.Nullable Boolean success) {
    this.success = success;
    return this;
  }

  /**
   * Get success
   * @return success
   */
  @javax.annotation.Nullable
  public Boolean getSuccess() {
    return success;
  }

  public void setSuccess(@javax.annotation.Nullable Boolean success) {
    this.success = success;
  }


  public ResponseMarkUseMultipleSchema returnCode(@javax.annotation.Nullable String returnCode) {
    this.returnCode = returnCode;
    return this;
  }

  /**
   * Result code if failed. In case of successful request: value is null
   * @return returnCode
   */
  @javax.annotation.Nullable
  public String getReturnCode() {
    return returnCode;
  }

  public void setReturnCode(@javax.annotation.Nullable String returnCode) {
    this.returnCode = returnCode;
  }


  public ResponseMarkUseMultipleSchema messageEn(@javax.annotation.Nullable String messageEn) {
    this.messageEn = messageEn;
    return this;
  }

  /**
   * Message notification in English
   * @return messageEn
   */
  @javax.annotation.Nullable
  public String getMessageEn() {
    return messageEn;
  }

  public void setMessageEn(@javax.annotation.Nullable String messageEn) {
    this.messageEn = messageEn;
  }


  public ResponseMarkUseMultipleSchema messageVi(@javax.annotation.Nullable String messageVi) {
    this.messageVi = messageVi;
    return this;
  }

  /**
   * Message notification in Vietnamese
   * @return messageVi
   */
  @javax.annotation.Nullable
  public String getMessageVi() {
    return messageVi;
  }

  public void setMessageVi(@javax.annotation.Nullable String messageVi) {
    this.messageVi = messageVi;
  }


  public ResponseMarkUseMultipleSchema data(@javax.annotation.Nullable List<ResponseMarkUseMultipleSchemaDataInner> data) {
    this.data = data;
    return this;
  }

  public ResponseMarkUseMultipleSchema addDataItem(ResponseMarkUseMultipleSchemaDataInner dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Detail items of voucher, if result is failed, response will return the first voucher code which is invalid
   * @return data
   */
  @javax.annotation.Nullable
  public List<ResponseMarkUseMultipleSchemaDataInner> getData() {
    return data;
  }

  public void setData(@javax.annotation.Nullable List<ResponseMarkUseMultipleSchemaDataInner> data) {
    this.data = data;
  }


  public ResponseMarkUseMultipleSchema transactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Transaction ID (if mark used successfully)
   * @return transactionId
   */
  @javax.annotation.Nullable
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
  }


  public ResponseMarkUseMultipleSchema billNumber(@javax.annotation.Nullable String billNumber) {
    this.billNumber = billNumber;
    return this;
  }

  /**
   * Bill number that vouchers were marked as used for.
   * @return billNumber
   */
  @javax.annotation.Nullable
  public String getBillNumber() {
    return billNumber;
  }

  public void setBillNumber(@javax.annotation.Nullable String billNumber) {
    this.billNumber = billNumber;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseMarkUseMultipleSchema responseMarkUseMultipleSchema = (ResponseMarkUseMultipleSchema) o;
    return Objects.equals(this.success, responseMarkUseMultipleSchema.success) &&
        Objects.equals(this.returnCode, responseMarkUseMultipleSchema.returnCode) &&
        Objects.equals(this.messageEn, responseMarkUseMultipleSchema.messageEn) &&
        Objects.equals(this.messageVi, responseMarkUseMultipleSchema.messageVi) &&
        Objects.equals(this.data, responseMarkUseMultipleSchema.data) &&
        Objects.equals(this.transactionId, responseMarkUseMultipleSchema.transactionId) &&
        Objects.equals(this.billNumber, responseMarkUseMultipleSchema.billNumber);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, returnCode, messageEn, messageVi, data, transactionId, billNumber);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseMarkUseMultipleSchema {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("    messageEn: ").append(toIndentedString(messageEn)).append("\n");
    sb.append("    messageVi: ").append(toIndentedString(messageVi)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    billNumber: ").append(toIndentedString(billNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("success");
    openapiFields.add("return_code");
    openapiFields.add("message_en");
    openapiFields.add("message_vi");
    openapiFields.add("data");
    openapiFields.add("transaction_id");
    openapiFields.add("bill_number");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResponseMarkUseMultipleSchema
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResponseMarkUseMultipleSchema.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResponseMarkUseMultipleSchema is not found in the empty JSON string", ResponseMarkUseMultipleSchema.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResponseMarkUseMultipleSchema.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResponseMarkUseMultipleSchema` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("return_code") != null && !jsonObj.get("return_code").isJsonNull()) && !jsonObj.get("return_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `return_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("return_code").toString()));
      }
      if ((jsonObj.get("message_en") != null && !jsonObj.get("message_en").isJsonNull()) && !jsonObj.get("message_en").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message_en` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message_en").toString()));
      }
      if ((jsonObj.get("message_vi") != null && !jsonObj.get("message_vi").isJsonNull()) && !jsonObj.get("message_vi").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message_vi` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message_vi").toString()));
      }
      if (jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) {
        JsonArray jsonArraydata = jsonObj.getAsJsonArray("data");
        if (jsonArraydata != null) {
          // ensure the json data is an array
          if (!jsonObj.get("data").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `data` to be an array in the JSON string but got `%s`", jsonObj.get("data").toString()));
          }

          // validate the optional field `data` (array)
          for (int i = 0; i < jsonArraydata.size(); i++) {
            ResponseMarkUseMultipleSchemaDataInner.validateJsonElement(jsonArraydata.get(i));
          };
        }
      }
      if ((jsonObj.get("transaction_id") != null && !jsonObj.get("transaction_id").isJsonNull()) && !jsonObj.get("transaction_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transaction_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transaction_id").toString()));
      }
      if ((jsonObj.get("bill_number") != null && !jsonObj.get("bill_number").isJsonNull()) && !jsonObj.get("bill_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bill_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bill_number").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResponseMarkUseMultipleSchema.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResponseMarkUseMultipleSchema' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResponseMarkUseMultipleSchema> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResponseMarkUseMultipleSchema.class));

       return (TypeAdapter<T>) new TypeAdapter<ResponseMarkUseMultipleSchema>() {
           @Override
           public void write(JsonWriter out, ResponseMarkUseMultipleSchema value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResponseMarkUseMultipleSchema read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResponseMarkUseMultipleSchema given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResponseMarkUseMultipleSchema
   * @throws IOException if the JSON string is invalid with respect to ResponseMarkUseMultipleSchema
   */
  public static ResponseMarkUseMultipleSchema fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResponseMarkUseMultipleSchema.class);
  }

  /**
   * Convert an instance of ResponseMarkUseMultipleSchema to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

