/*
 * Merchant APIs
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.RequestCheckMultipleBodySchema;
import org.openapitools.client.model.RequestMarkUseMultipleBodySchema;
import org.openapitools.client.model.RequestReservedBodySchema;
import org.openapitools.client.model.RequestUnReservedBodySchema;
import org.openapitools.client.model.ResponseCheckMultipleSchema;
import org.openapitools.client.model.ResponseMarkUseMultipleSchema;
import org.openapitools.client.model.ResponseReservedSchema;
import org.openapitools.client.model.ResponseUnReservedSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GotItMerchantApi
 */
@Disabled
public class GotItMerchantApiTest {

    private final GotItMerchantApi api = new GotItMerchantApi();

    /**
     * Check multiple vouchers are valid or not
     *
     * Check multiple vouchers are valid or not
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkMultipleTest() throws ApiException {
        RequestCheckMultipleBodySchema requestCheckMultipleBodySchema = null;
        ResponseCheckMultipleSchema response = api.checkMultiple(requestCheckMultipleBodySchema);
        // TODO: test validations
    }

    /**
     * Reserved multiple vouchers for a fixed bill number.
     *
     * Reserved multiple vouchers for a fixed bill number.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void reservedTest() throws ApiException {
        RequestReservedBodySchema requestReservedBodySchema = null;
        ResponseReservedSchema response = api.reserved(requestReservedBodySchema);
        // TODO: test validations
    }

    /**
     * Reserved multiple vouchers for a fixed bill number.
     *
     * Reserved multiple vouchers for a fixed bill number.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unreservedTest() throws ApiException {
        RequestUnReservedBodySchema requestUnReservedBodySchema = null;
        ResponseUnReservedSchema response = api.unreserved(requestUnReservedBodySchema);
        // TODO: test validations
    }

    /**
     * Reserved multiple vouchers for a fixed bill number.
     *
     * Reserved multiple vouchers for a fixed bill number.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void useMultipleTest() throws ApiException {
        RequestMarkUseMultipleBodySchema requestMarkUseMultipleBodySchema = null;
        ResponseMarkUseMultipleSchema response = api.useMultiple(requestMarkUseMultipleBodySchema);
        // TODO: test validations
    }

}
